#!/bin/bash

echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker build -f Dockerbuild.jenkins -t liriorg/ostree-image-creator .
docker push liriorg/ostree-image-creator
